# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
warnings_are_errors: true
env:
  global:
    - NOT_CRAN=false
before_install:
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
r_binary_packages:
  - covr
addons:
  apt:
    packages:
      - libapparmor-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - poppler-data
      - valgrind
